name: planets
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  # flutter_bloc: ^7.0.0
  # equatable: ^2.0.0
  # bloc: ^7.0.0
  # flutter_bloc_navigation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/cosmic_1.png
    - assets/images/cosmic_logo.png
    - assets/images/flutter_logo.png
    - assets/images/ellipse_1.png
    - assets/images/ellipse_2.png
    - assets/images/ellipse_3.png
    - assets/images/shad.png
    - assets/images/background_black.png
    - assets/images/logo_2.png
    - assets/images/home_1.png
    - assets/images/home_2.png
    - assets/images/home_3.png
    - assets/images/mars_image.png
    - assets/images/venus_image.png
    - assets/images/earth_image.png
    - assets/json/planet.json

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
